import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ToasterContext from './context/Toaster'
import AuhtContex from './context/AuhtContex'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Juki Chat app ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <AuhtContex>
       <ToasterContext/>
        {children}
       </AuhtContex>
        </body>
    </html>
  )
}
